name: PHPUnit Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: cp api.corvesive.com/.env.example api.corvesive.com/.env

      - name: Install Dependencies
        working-directory: api.corvesive.com
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate key
        working-directory: api.corvesive.com
        run: php artisan key:generate

      - name: Directory Permissions
        working-directory: api.corvesive.com
        run: chmod -R 777 storage bootstrap/cache

      - name: Optimize Project
        working-directory: api.corvesive.com
        run: php artisan optimize:clear

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: api.corvesive.com
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root  # Make sure to set the DB_PASSWORD
        run: |
          php artisan migrate
          php artisan test
